version: '3.7'

services:
  backend:
    hostname: backend.docker
    container_name: oksa-backend
    env_file:
      - ./Backend/.env
    build:
      context: ./Backend
      target: development
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
  frontend:
    hostname: frontend.docker
    container_name: oksa-frontend
    build:
      context: ./Frontend
      target: development
    volumes:
      - ./Frontend:/usr/src/nuxt-app
      - /usr/src/nuxt-app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    networks:
      - webnet
    restart: unless-stopped
  postgres:
    hostname: psql.docker
    container_name: oksa-database
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 9000:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    hostname: redis.docker
    container_name: oksa-redis
    image: redis:6
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata:
