import {MigrationInterface, QueryRunner} from "typeorm";

export class oksaMigration1618250041367 implements MigrationInterface {
    name = 'oksaMigration1618250041367'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "organisations" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" uuid NOT NULL, "lastModified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastModifiedBy" uuid NOT NULL, "name" character varying(300) NOT NULL, CONSTRAINT "PK_e28710839e3183f52669df498a5" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "profiles" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdBy" uuid NOT NULL, "lastModified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastModifiedBy" uuid NOT NULL, "name" character varying(300) NOT NULL, "email" character varying(300), "phoneNumber" character varying(36), "ip" text, "userUuid" uuid, CONSTRAINT "UQ_5b49bd22c967ce2829ca8f17720" UNIQUE ("email"), CONSTRAINT "UQ_8197446e07563b8f4c34f69881f" UNIQUE ("phoneNumber"), CONSTRAINT "REL_ad26f60abdd1f712200831d35f" UNIQUE ("userUuid"), CONSTRAINT "PK_2c0c7196c89bdcc9b04f29f3fe6" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "logins" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "loginCode" character varying(6) NOT NULL, "codeUsed" boolean NOT NULL, "userUUID" character varying(36) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PK_3fa6dfd9c880cf06ab19816fd0d" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "organisations_users_profiles" ("organisationsUuid" uuid NOT NULL, "profilesUuid" uuid NOT NULL, CONSTRAINT "PK_d4e9d4fb9ef462bd933c5338dfb" PRIMARY KEY ("organisationsUuid", "profilesUuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e935310791f2d1e4091209b7b3" ON "organisations_users_profiles" ("organisationsUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a0c030e77a63054608cef60ef" ON "organisations_users_profiles" ("profilesUuid") `);
        await queryRunner.query(`CREATE TABLE "meetings_authorized_users_users" ("meetingsUuid" uuid NOT NULL, "usersUuid" uuid NOT NULL, CONSTRAINT "PK_f82e2910e1dfab35529abc12e15" PRIMARY KEY ("meetingsUuid", "usersUuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_486f56b0164bb7db47bca1015f" ON "meetings_authorized_users_users" ("meetingsUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_27a9a054491732acc0cc3ed38a" ON "meetings_authorized_users_users" ("usersUuid") `);
        await queryRunner.query(`ALTER TABLE "meetings" DROP COLUMN "authorizedUsers"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "codeUsed"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "meetings"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "loginCode"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "cards"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP COLUMN "author"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP COLUMN "meetingID"`);
        await queryRunner.query(`ALTER TABLE "cards" ADD "authorUuid" uuid`);
        await queryRunner.query(`ALTER TABLE "cards" ADD "meetingUuid" uuid`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "uuid" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."uuid" IS NULL`);
        // await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "PK_4cd89775d1ca34ae4110fc24fc9" PRIMARY KEY ("uuid")`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "created" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."created" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "created" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "createdBy" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."createdBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "lastModified" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."lastModified" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "lastModified" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "lastModifiedBy" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."lastModifiedBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "id" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."id" IS NULL`);
        // await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "UQ_aa73be861afa77eb4ed31f3ed57" UNIQUE ("id")`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "creatorName" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."creatorName" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "password" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."password" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "uuid" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."uuid" IS NULL`);
        // await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_951b8f1dfc94ac1d0301a14b7e1" PRIMARY KEY ("uuid")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."created" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdBy" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."createdBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "lastModified" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."lastModified" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "lastModified" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "lastModifiedBy" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."lastModifiedBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "authToken" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "refreshToken" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."refreshToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "uuid" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."uuid" IS NULL`);
        // await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "PK_cb3789f0e79e124e5753da0010a" PRIMARY KEY ("uuid")`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "created" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."created" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "created" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "createdBy" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."createdBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "lastModified" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."lastModified" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "lastModified" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "lastModifiedBy" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."lastModifiedBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "content" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."content" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "deleted" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."deleted" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."title" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_806da3a699248dec86bd083167" ON "cards" ("meetingUuid") `);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_ad26f60abdd1f712200831d35f2" FOREIGN KEY ("userUuid") REFERENCES "users"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "FK_cbb0c0798d4606401fe5ccb0746" FOREIGN KEY ("authorUuid") REFERENCES "users"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cards" ADD CONSTRAINT "FK_806da3a699248dec86bd083167c" FOREIGN KEY ("meetingUuid") REFERENCES "meetings"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organisations_users_profiles" ADD CONSTRAINT "FK_e935310791f2d1e4091209b7b3b" FOREIGN KEY ("organisationsUuid") REFERENCES "organisations"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organisations_users_profiles" ADD CONSTRAINT "FK_2a0c030e77a63054608cef60ef4" FOREIGN KEY ("profilesUuid") REFERENCES "profiles"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings_authorized_users_users" ADD CONSTRAINT "FK_486f56b0164bb7db47bca1015f8" FOREIGN KEY ("meetingsUuid") REFERENCES "meetings"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings_authorized_users_users" ADD CONSTRAINT "FK_27a9a054491732acc0cc3ed38a4" FOREIGN KEY ("usersUuid") REFERENCES "users"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "meetings_authorized_users_users" DROP CONSTRAINT "FK_27a9a054491732acc0cc3ed38a4"`);
        await queryRunner.query(`ALTER TABLE "meetings_authorized_users_users" DROP CONSTRAINT "FK_486f56b0164bb7db47bca1015f8"`);
        await queryRunner.query(`ALTER TABLE "organisations_users_profiles" DROP CONSTRAINT "FK_2a0c030e77a63054608cef60ef4"`);
        await queryRunner.query(`ALTER TABLE "organisations_users_profiles" DROP CONSTRAINT "FK_e935310791f2d1e4091209b7b3b"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "FK_806da3a699248dec86bd083167c"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "FK_cbb0c0798d4606401fe5ccb0746"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_ad26f60abdd1f712200831d35f2"`);
        await queryRunner.query(`DROP INDEX "IDX_806da3a699248dec86bd083167"`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."title" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."deleted" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "deleted" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."content" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "content" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."lastModifiedBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "lastModifiedBy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "lastModified" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."lastModified" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "lastModified" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."createdBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "createdBy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "created" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."created" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "created" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cards" DROP CONSTRAINT "PK_cb3789f0e79e124e5753da0010a"`);
        await queryRunner.query(`COMMENT ON COLUMN "cards"."uuid" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cards" ALTER COLUMN "uuid" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."refreshToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "refreshToken" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."authToken" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "authToken" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."lastModifiedBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "lastModifiedBy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "lastModified" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."lastModified" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "lastModified" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."createdBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdBy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."created" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_951b8f1dfc94ac1d0301a14b7e1"`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."uuid" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "uuid" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."password" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "password" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."creatorName" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "creatorName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "UQ_aa73be861afa77eb4ed31f3ed57"`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "id" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."lastModifiedBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "lastModifiedBy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "lastModified" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."lastModified" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "lastModified" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."createdBy" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "createdBy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "created" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."created" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "created" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "PK_4cd89775d1ca34ae4110fc24fc9"`);
        await queryRunner.query(`COMMENT ON COLUMN "meetings"."uuid" IS NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "uuid" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cards" DROP COLUMN "meetingUuid"`);
        await queryRunner.query(`ALTER TABLE "cards" DROP COLUMN "authorUuid"`);
        await queryRunner.query(`ALTER TABLE "cards" ADD "meetingID" character varying(11)`);
        await queryRunner.query(`ALTER TABLE "cards" ADD "author" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "cards" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "loginCode" character varying(6)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phoneNumber" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "meetings" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "codeUsed" boolean`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD "authorizedUsers" text`);
        await queryRunner.query(`DROP INDEX "IDX_27a9a054491732acc0cc3ed38a"`);
        await queryRunner.query(`DROP INDEX "IDX_486f56b0164bb7db47bca1015f"`);
        await queryRunner.query(`DROP TABLE "meetings_authorized_users_users"`);
        await queryRunner.query(`DROP INDEX "IDX_2a0c030e77a63054608cef60ef"`);
        await queryRunner.query(`DROP INDEX "IDX_e935310791f2d1e4091209b7b3"`);
        await queryRunner.query(`DROP TABLE "organisations_users_profiles"`);
        await queryRunner.query(`DROP TABLE "logins"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP TABLE "organisations"`);
    }

}
